name: picture_game
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.24.0
  flutter_riverpod: ^2.0.0
  responsive_sizer: ^3.1.1
  cloud_firestore: ^3.5.0
  firebase_auth: ^3.11.0
  http: ^0.13.5
  google_fonts: ^3.0.1
  cached_network_image: ^3.2.2
  pin_code_fields: ^7.4.0
  backdrop: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

dependency_overrides:
  firebase_core_platform_interface: 4.5.1

flutter:
  uses-material-design: true
  fonts:
    - family: pinkblue
      fonts: 
        - asset: assets/fonts/pinkblue.otf 
    - family: sunny
      fonts: 
        - asset: assets/fonts/sunny.otf 

